### ISSUE TITLE
Running issues 

### ISSUE THREAD

**Issue by deveshruttala** [nnmarcoo/img#1]
can you help me how to run this file and what are the dependencies that are required

**Comment by nnmarcoo** [comment]
The app is in early beta, so there are many unfinished or broken features, but I'll try my best:

To compile and run the source code yourself, you need to install [Rust](https://www.rust-lang.org/tools/install) and [Tauri](https://tauri.app/). After installing Rust, I suggest running `cargo install create-tauri-app --locked` and `cargo install tauri-cli` to install Tauri. To compile and run the project, you can run `cargo tauri dev` while you're in the project directory. Be aware, that I can't summarize everything here, so it's best to look into the [guides](https://tauri.app/v1/guides/) and [quick start](https://tauri.app/v1/guides/getting-started/setup/) for more information on Tauri projects.

And if you're asking how to install and test the beta, you can navigate to [releases](https://github.com/nnmarcoo/img/releases) and download the latest installer for your operating system. In the future, the [img](https://github.com/nnmarcoo/img) repo will have documentation and a complete feature set.
